"""Dependency inversion ports."""

from typing import Protocol

from git_ai_agent.domain.models import ReviewReport


class AIReviewer(Protocol):
    """Optional review provider boundary."""

    def review(self, diff: str) -> str: ...


class RepositoryPort(Protocol):
    """Git repository boundary."""

    @property
    def root(self) -> str: ...
    def branch(self) -> str: ...
    def diff(self) -> str: ...
    def fingerprint(self) -> str: ...
    def changed_files(self) -> list[tuple[str, str]]: ...
    def add(self, files: list[str]) -> None: ...
    def commit(self, message: str) -> str: ...
    def push(self) -> str: ...


class ReviewerPort(Protocol):
    """Review boundary."""

    def review(self, repository: RepositoryPort) -> ReviewReport: ...
